export const allItems = [
    { _id: "100", title: "All Catagories" },
    { _id: "2", title: "Alexa Skills" },
    { _id: "3", title: "Amazon Divices" },
    { _id: "4", title: "Amazon fashion" },
    { _id: "5", title: "Amazon Pharmacy" },
    { _id: "6", title: "Appliances" },
    { _id: "7", title: "Apps & Games" },
    { _id: "8", title: "Baby" },
    { _id: "9", title: "Beauty" },
    { _id: "10", title: "Books" },
    { _id: "11", title: "Car & Motorbikes" },
    { _id: "12", title: "Electronics" },
    { _id: "13", title: "Computers & Accessories" },
    { _id: "14", title: "Furniture" },
    { _id: "15", title: "Garden & OutClothing & Accessoriesdoors" },
    { _id: "16", title: "Gift Cards" },
    { _id: "17", title: "Health & personal Care" },
  ]